### ISSUE TITLE
文字描述错误

### ISSUE THREAD

**Issue by wuminhao** [MicrosoftDocs/MIMDocs.zh-cn#17]
所需软件部分，SQL数据库错误的写成了SOL Server 2014
英文版无此问题，只有中文版写错

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: efad1729-8efe-22d1-a376-fbd1b247670d
* Version Independent ID: bfbe1ec1-efca-1dc1-72d9-a541383c5d0f
* Content: [PAM 软件要求](https://docs.microsoft.com/zh-cn/microsoft-identity-manager/pam/hardware-software-requirements#feedback)
* Content Source: [MIMDocs/pam/hardware-software-requirements.md](https://github.com/MicrosoftDocs/MIMDocs.zh-cn/blob/live/MIMDocs/pam/hardware-software-requirements.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by srvbpigh** [comment]
Hello, @wuminhao
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@wuminhao
感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/microsoft-identity-manager/pam/hardware-software-requirements#feedback 

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team
