### ISSUE TITLE
The script in step 2 does not work

### ISSUE THREAD

**Issue by wsy** [MicrosoftDocs/MIMDocs.zh-cn#18]
In line 3 of the script and line 6 of the script in Step 2, you created two AdUser with same name MIMMA.
```Powershell
New-ADUser -SamAccountName MIMINSTALL -name MIMMA
New-ADUser -SamAccountName MIMMA -name MIMMA
```
Also, if you copy and paste. this script to Powershell, you will find another similar error.
I believe these two low level errors can be prevented if the author verified his/her document by setting up a sample environment with the steps and sample scripts in this document.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b63b3e40-9767-a459-3c57-3aad83026b74
* Version Independent ID: d1cf0874-08cc-4c70-44d5-a1a625bdfe42
* Content: [设置 Microsoft Identity Manager 2016 的域](https://docs.microsoft.com/zh-cn/microsoft-identity-manager/preparing-domain#feedback)
* Content Source: [MIMDocs/preparing-domain.md](https://github.com/MicrosoftDocs/MIMDocs.zh-cn/blob/live/MIMDocs/preparing-domain.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by wsy** [comment]
https://github.com/MicrosoftDocs/MIMDocs/issues/103
So I found out this link. This issue has been here since July 2018.

**Comment by srvbpigh** [comment]
Hello, @wsy
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/MIMDocs #174](https://github.com/MicrosoftDocs/MIMDocs/issues/174) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @wsy

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/MIMDocs/issues/174

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
