### ISSUE TITLE
Your sample script contains a lot of '–' instead of '-'

### ISSUE THREAD

**Issue by wsy** [MicrosoftDocs/MIMDocs.zh-cn#19]
So, your author never noticed the highlighting problem in your sample script.
Only the 'Add-ADGroupMember' and the last two 'Set-ADUser' command have some of their options highlighted and all other parameters in all other commands in this article(except for the Add-ADGroupMember command) failed to be highlighted.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b63b3e40-9767-a459-3c57-3aad83026b74
* Version Independent ID: d1cf0874-08cc-4c70-44d5-a1a625bdfe42
* Content: [设置 Microsoft Identity Manager 2016 的域](https://docs.microsoft.com/zh-cn/microsoft-identity-manager/preparing-domain#feedback)
* Content Source: [MIMDocs/preparing-domain.md](https://github.com/MicrosoftDocs/MIMDocs.zh-cn/blob/live/MIMDocs/preparing-domain.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by srvbpigh** [comment]
Hello, @wsy
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by wsy** [comment]
Actually this issue also exists in English version of your documents.

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/MIMDocs #173](https://github.com/MicrosoftDocs/MIMDocs/issues/173) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @wsy

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/MIMDocs/issues/173

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
